"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var users_1 = require("../controller/users");
var user_validation_1 = require("../validation/user.validation");
var router = express_1.default.Router();
router.get("/:id", users_1.getUser);
router.put("/:id", user_validation_1.validateUpdateData, users_1.updateUser);
router.delete("/:id", users_1.deleteUser);
exports.default = router;
