CREATE TABLE IF NOT EXISTS "users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(255) UNIQUE NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "street_address" varchar(255),
  "city" varchar(255),
  "state" varchar(255),
  "zip_code" varchar(20),
  "country" varchar(255),
  "role" varchar(255) NOT NULL DEFAULT 'user'
);

CREATE TABLE IF NOT EXISTS "products" (
  "product_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "description" text,
  "price" decimal NOT NULL,
  "image_url" varchar(255),
  "category_id" int
);

CREATE TABLE IF NOT EXISTS "categories" (
  "category_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "carts" (
  "cart_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "cart_items" (
  "cart_item_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cart_id" integer NOT NULL,
  "product_id" integer NOT NULL,
  "quantity" integer NOT NULL
);

CREATE TABLE IF NOT EXISTS "orders" (
  "order_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "order_date" timestamptz NOT NULL DEFAULT (now()),
  "total_amount" decimal NOT NULL
);

CREATE TABLE IF NOT EXISTS "order_items" (
  "order_item_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" integer NOT NULL,
  "product_id" integer NOT NULL,
  "quantity" integer NOT NULL,
  "price" decimal NOT NULL
);

CREATE TABLE IF NOT EXISTS "checkouts" (
  "checkout_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "checkout_date" timestamptz NOT NULL DEFAULT (now()),
  "total_amount" decimal NOT NULL
);

DO $$ 
BEGIN 
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'checkouts_user_id_fkey'
  ) THEN
    ALTER TABLE "checkouts" ADD CONSTRAINT checkouts_user_id_fkey FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'carts_user_id_fkey'
  ) THEN
    ALTER TABLE "carts" ADD CONSTRAINT carts_user_id_fkey FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'cart_items_cart_id_fkey'
  ) THEN
    ALTER TABLE "cart_items" ADD CONSTRAINT cart_items_cart_id_fkey FOREIGN KEY ("cart_id") REFERENCES "carts" ("cart_id");
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'cart_items_product_id_fkey'
  ) THEN
    ALTER TABLE "cart_items" ADD CONSTRAINT cart_items_product_id_fkey FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'orders_user_id_fkey'
  ) THEN
    ALTER TABLE "orders" ADD CONSTRAINT orders_user_id_fkey FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'order_items_order_id_fkey'
  ) THEN
    ALTER TABLE "order_items" ADD CONSTRAINT order_items_order_id_fkey FOREIGN KEY ("order_id") REFERENCES "orders" ("order_id");
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'order_items_product_id_fkey'
  ) THEN
    ALTER TABLE "order_items" ADD CONSTRAINT order_items_product_id_fkey FOREIGN KEY ("product_id") REFERENCES "products" ("product_id");
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'products_category_id_fkey'
  ) THEN
    ALTER TABLE "products" ADD CONSTRAINT products_category_id_fkey FOREIGN KEY ("category_id") REFERENCES "categories" ("category_id");
  END IF;
END $$;